### ISSUE TITLE
工程编译报错

### ISSUE THREAD

**Issue by xiangxm** [lzan13/VMMatch#2]
hi ，
`ERROR: Failed to resolve: com.vmloft.library:vmtools:0.9.0
Show in Project Structure dialog
Affected Modules: app, vmim`

vmtools ===》这个会报错

**Comment by lzan13** [comment]
是直接 clone 下来编译报错吗？还是你引用了之后报错

**Comment by xiangxm** [comment]
直接clone 下来编译报错。 后来我下了你的VMLibrary 本地引用了这个库

**Comment by lzan13** [comment]
vmtools 释放在 jCenter 上的，应该是没有加载到库，可以清空缓存试下，或者翻墙试试

**Comment by xiangxm** [comment]
OK  ，多谢分享。 研究一下
